Implement a logical char device driver & plug the r/w operation of aesdsocket App with this driver

diff --git a/base_external/rootfs_overlay/etc/init.d/S98lddmodules b/base_external/rootfs_overlay/etc/init.d/S98lddmodules
--- a/base_external/rootfs_overlay/etc/init.d/S98lddmodules
+++ b/base_external/rootfs_overlay/etc/init.d/S98lddmodules
@@ -9,14 +9,19 @@
 ### END INIT INFO
 case "$1" in
   start)
-    echo "Loading ldd kernel modules..."
-    modprobe scull
-    modprobe faulty
-    modprobe hello
+    echo "Loading scull kernel modules..."
+    modprobe scull || echo "ERROR: scull failed"
+    echo "Loading aesdchar..."
+    /etc/load_aesdchar || echo "ERROR: aesdchar failed"
+    echo "Loading hello kernel module..."
+    modprobe hello || echo "ERROR: hello failed"
+    echo "Loading faulty kernel module..."
+    modprobe faulty || echo "ERROR: faulty failed"
     ;;
   stop)
     echo "Unloading ldd kernel modules..."
     rmmod hello
+    /etc/unload_aesdchar || echo "ERROR: aesdchar failed"
     rmmod faulty
     rmmod scull
     ;;
